language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

gemfile:
 - Gemfile

branches:
  only:
    - master

before_install: gem update bundler
script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head